"""
Structured File Query Engine

Loads CSV/XLSX/XLS files into an in-memory pandas DataFrame and answers
natural language queries against them using an LLM-generated pandas
expression executed in a restricted sandbox.

Pipeline:
  UploadedFile.content_text (raw bytes re-parsed) or stored content
      ↓
  pd.DataFrame
      ↓
  NL query  →  LLM  →  pandas code string
      ↓
  sandboxed exec(code, {"df": df})
      ↓
  StructuredFileResult (rows, columns, row_count, …)
"""

from __future__ import annotations

import io
import logging
import re
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class StructuredFileResult:
    """Outcome of a structured-file NL query."""
    rows: List[Dict[str, Any]]
    columns: List[str]
    row_count: int
    query_code: str            # Pandas expression generated by LLM (for debug)
    file_id: str
    filename: str
    is_truncated: bool
    execution_time_ms: float
    error: Optional[str] = None
    # Pre-aggregated view (populated by caller / viz generator)
    pre_aggregated: Optional[List[Dict[str, Any]]] = None


# ---------------------------------------------------------------------------
# Safety helpers
# ---------------------------------------------------------------------------

# Tokens that must not appear in generated pandas code (simple blocklist).
_BLOCKED_PATTERNS = re.compile(
    r"\b(import|exec|eval|open|os\.|sys\.|subprocess|__builtins__|globals|locals"
    r"|getattr|setattr|delattr|compile|breakpoint|input|print)\b",
    re.IGNORECASE,
)

_MAX_RESULT_ROWS = 10_000   # Hard cap on rows returned to caller
_MAX_INPUT_ROWS = 500_000   # Files larger than this are sampled before LLM call


def _is_safe_code(code: str) -> bool:
    """Return True if the LLM-generated code passes the safety check."""
    return not bool(_BLOCKED_PATTERNS.search(code))


def _sanitize_code(code: str) -> str:
    """Strip markdown fences and leading/trailing whitespace from LLM output."""
    code = code.strip()
    # Remove ```python … ``` or ``` … ``` wrappers
    code = re.sub(r"^```(?:python)?\s*", "", code)
    code = re.sub(r"\s*```$", "", code)
    return code.strip()


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------

class StructuredFileEngine:
    """
    Loads structured files (CSV / XLSX / XLS) into pandas and answers
    natural language queries against them.

    Small files (<= _MAX_INPUT_ROWS rows): fully in-memory.
    Large files: sampled to _MAX_INPUT_ROWS rows before sending schema to LLM.
    """

    def __init__(self, llm_client=None):
        """
        Args:
            llm_client: Optional pre-constructed LLM client.  When None the
                engine imports `app.llm` lazily so tests can inject a mock.
        """
        self._llm = llm_client  # lazily resolved in _get_llm()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def load_dataframe(self, raw_bytes: bytes, filename: str) -> "pd.DataFrame":
        """Parse raw bytes into a DataFrame.

        Supports CSV, XLSX, XLS.  Returns an empty DataFrame on error.
        """
        import pandas as pd  # local import — optional dependency

        fname = (filename or "").lower()
        try:
            if fname.endswith(".csv"):
                # Try UTF-8 first, fall back to latin-1
                try:
                    df = pd.read_csv(io.BytesIO(raw_bytes), low_memory=False)
                except UnicodeDecodeError:
                    df = pd.read_csv(
                        io.BytesIO(raw_bytes), encoding="latin-1", low_memory=False
                    )
            elif fname.endswith((".xlsx", ".xls")):
                df = pd.read_excel(io.BytesIO(raw_bytes))
            else:
                logger.warning("[STRUCT_FILE] Unknown extension for %s, trying CSV", filename)
                df = pd.read_csv(io.BytesIO(raw_bytes), low_memory=False)
        except Exception as exc:
            logger.error("[STRUCT_FILE] Failed to parse %s: %s", filename, exc)
            return pd.DataFrame()

        # Sample if oversized
        if len(df) > _MAX_INPUT_ROWS:
            logger.warning(
                "[STRUCT_FILE] File %s has %d rows — sampling to %d",
                filename, len(df), _MAX_INPUT_ROWS,
            )
            df = df.sample(n=_MAX_INPUT_ROWS, random_state=42).reset_index(drop=True)

        return df

    async def query(
        self,
        df: "pd.DataFrame",
        user_query: str,
        file_id: str = "",
        filename: str = "",
        conversation_history: str = "",
    ) -> StructuredFileResult:
        """Run a natural-language query against a DataFrame.

        1. Ask LLM for a pandas expression.
        2. Validate it is safe.
        3. Execute in a restricted namespace.
        4. Return StructuredFileResult.
        """
        import pandas as pd

        start = time.perf_counter()

        if df.empty:
            return StructuredFileResult(
                rows=[], columns=[], row_count=0,
                query_code="# empty dataframe",
                file_id=file_id, filename=filename,
                is_truncated=False,
                execution_time_ms=0.0,
                error="File is empty or could not be parsed.",
            )

        # Build schema description for the LLM prompt
        df_info = self._describe_dataframe(df)

        # Ask LLM for pandas code
        code = await self._nl_to_pandas_code(
            user_query=user_query,
            df_info=df_info,
            conversation_history=conversation_history,
        )
        code = _sanitize_code(code)

        # Execute in sandbox
        result_df, exec_error = self._execute_safe(df, code)
        if exec_error:
            logger.warning(
                "[STRUCT_FILE] Sandbox exec failed (%s), falling back to full data", exec_error
            )
            result_df = df  # safe fallback
            code = "# exec failed — returning full dataframe"

        elapsed_ms = (time.perf_counter() - start) * 1000

        # Truncate if needed
        is_truncated = len(result_df) > _MAX_RESULT_ROWS
        if is_truncated:
            result_df = result_df.head(_MAX_RESULT_ROWS)

        rows = result_df.to_dict("records")
        # Make values JSON-safe (convert numpy scalars, NaN → None, etc.)
        rows = _json_safe(rows)

        return StructuredFileResult(
            rows=rows,
            columns=list(result_df.columns),
            row_count=len(rows),
            query_code=code,
            file_id=file_id,
            filename=filename,
            is_truncated=is_truncated,
            execution_time_ms=round(elapsed_ms, 1),
        )

    # ------------------------------------------------------------------
    # LLM interaction
    # ------------------------------------------------------------------

    async def _nl_to_pandas_code(
        self,
        user_query: str,
        df_info: str,
        conversation_history: str = "",
    ) -> str:
        """Ask the LLM to translate a natural language query to pandas code.

        Returns a single pandas expression string like:
            df[df['region'] == 'North'].groupby('product').agg({'sales': 'sum'})

        On any failure returns "df" (the whole dataframe as a safe fallback).
        """
        history_block = (
            f"\nConversation history:\n{conversation_history}\n"
            if conversation_history.strip()
            else ""
        )

        prompt = f"""\
You are a pandas expert. You will be given a DataFrame schema and a natural language query.
Output ONLY a single valid pandas expression that answers the query — nothing else.
Do not include explanations, comments, imports, or markdown fences.
The variable name is always `df`.
{history_block}
DataFrame schema:
{df_info}

User query: {user_query}

Pandas expression:"""

        try:
            llm = await self._get_llm()
            raw_response = await llm.chat(prompt)
            code = _sanitize_code(raw_response or "df")
        except Exception as exc:
            logger.error("[STRUCT_FILE] LLM call failed: %s", exc)
            code = "df"

        if not _is_safe_code(code):
            logger.warning("[STRUCT_FILE] Unsafe code rejected: %s", code[:200])
            code = "df"

        logger.debug("[STRUCT_FILE] Generated code: %s", code[:300])
        return code

    # ------------------------------------------------------------------
    # Sandboxed execution
    # ------------------------------------------------------------------

    def _execute_safe(
        self, df: "pd.DataFrame", code: str
    ) -> "tuple[pd.DataFrame, Optional[str]]":
        """Execute pandas code in a restricted namespace.

        Returns (result_df, error_message).  error_message is None on success.
        """
        import pandas as pd

        namespace: Dict[str, Any] = {"df": df}
        try:
            result = eval(code, {"__builtins__": {}}, namespace)  # noqa: S307
            if isinstance(result, pd.DataFrame):
                return result, None
            elif isinstance(result, pd.Series):
                return result.to_frame(), None
            else:
                # Scalar result — wrap in a single-cell DataFrame
                return pd.DataFrame({"result": [result]}), None
        except Exception as exc:
            return df, str(exc)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _describe_dataframe(self, df: "pd.DataFrame") -> str:
        """Return a compact human-readable schema + sample for the LLM."""
        import pandas as pd

        col_info = []
        for col in df.columns:
            dtype = str(df[col].dtype)
            n_unique = df[col].nunique()
            if df[col].dtype == object:
                sample_vals = df[col].dropna().unique()[:5].tolist()
            else:
                sample_vals = df[col].dropna().head(3).tolist()
            col_info.append(
                f"  {col!r} ({dtype}, {n_unique} unique) — e.g. {sample_vals}"
            )

        header = f"Rows: {len(df)}, Columns: {len(df.columns)}"
        return header + "\n" + "\n".join(col_info)

    async def _get_llm(self):
        """Lazily resolve the LLM client."""
        if self._llm is not None:
            return self._llm
        from app import llm as app_llm  # lazy to avoid circular imports
        return app_llm


# ---------------------------------------------------------------------------
# Singleton factory
# ---------------------------------------------------------------------------

_engine_instance: Optional[StructuredFileEngine] = None


def get_structured_file_engine() -> StructuredFileEngine:
    """Return the global StructuredFileEngine singleton."""
    global _engine_instance
    if _engine_instance is None:
        _engine_instance = StructuredFileEngine()
    return _engine_instance


# ---------------------------------------------------------------------------
# JSON-safe serializer
# ---------------------------------------------------------------------------

def _json_safe(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Convert numpy scalars, NaN, NaT, etc. to Python-native JSON-safe types."""
    import math

    def _convert(v: Any) -> Any:
        if v is None:
            return None
        # numpy scalar types
        try:
            import numpy as np
            if isinstance(v, (np.integer,)):
                return int(v)
            if isinstance(v, (np.floating,)):
                f = float(v)
                return None if math.isnan(f) or math.isinf(f) else f
            if isinstance(v, np.bool_):
                return bool(v)
            if isinstance(v, np.ndarray):
                return v.tolist()
        except ImportError:
            pass
        # pandas NaT / NA
        try:
            import pandas as pd
            if pd.isna(v):  # type: ignore[arg-type]
                return None
        except (ImportError, TypeError, ValueError):
            pass
        # python float NaN / inf
        if isinstance(v, float):
            return None if (math.isnan(v) or math.isinf(v)) else v
        return v

    return [{k: _convert(val) for k, val in row.items()} for row in rows]
